### ISSUE TITLE
PySMT install

### ISSUE THREAD

**Issue by bellert** [dwavesystems/homebase#28]
PySMT installation requires executing a command (`pysmt-install --env`) to obtain a string with another command to execute to update `PYTHONPATH`
https://github.com/pysmt/pysmt#installation

**Comment by bellert** [comment]
Also could get `/site-packages/` directory and add `smt.pth` file
https://github.com/dwavesystems/penaltymodel_maxgap/blob/master/.travis.yml

**Comment by arcondello** [comment]
Closing as stale
