### ISSUE TITLE
XDG usage

### ISSUE THREAD

**Issue by randomir** [dwavesystems/homebase#30]
Config dirs (on Linux) returned according to XDG (X Windows Desktop) specs:
```
/etc/xdg/xdg-ubuntu
/usr/share/upstart/xdg
/etc/xdg
```
Data dirs:
```
/usr/share/ubuntu
/usr/share/gnome
/usr/local/share
/usr/share
/var/lib/snapd/desktop
/var/lib/snapd/desktop
```

For the default system-wide config dir, `homebase` returns:
```
>>> homebase.site_config_dir("myapp", "author", create=False)
'/etc/xdg/xdg-ubuntu/myapp'
```

I was expecting to see something like `/usr/local/share/myapp` and `/etc/local/myapp`.

**Comment by orenshk** [comment]
Hmm...It seems that Ubuntu has its own opinion on how to fill the $XDG_DATA_DIRS AND $XDG_CONFIG_DIRS variables.

On the spectrum of doing nothing to ignoring the XDG spec, what's the sensible thing to do here?

**Comment by randomir** [comment]
I'm not sure how to solve this. The actual (long) list of obscure config file locations doesn't bother me (since there's little chance of `myapp` to hold config files there), but I would like to see `/etc/myapp` and `/etc/local/myapp` somewhere in that list.

Or maybe I'm completely wrong, and all user apps should store their config files in `/etc/xdg/xdg-ubuntu` or `/usr/share/upstart/xdg` or `/etc/xdg`. Will have to check what's the expected behaviour of Linux apps these days.

**Comment by randomir** [comment]
Well, looks like XDG is the best we have. So much for the year of Linux on desktop. ;)

In a lack of better option (alternative), I'll close this issue for now.
